// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtcwzyyacyekklhtbwrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Y3d6eXlhY3lla2tsaHRid3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTQ4NjMsImV4cCI6MjA2MTA3MDg2M30.IKQioRI05aoc8HKoYHHGfz7uR0VpNjo1cZC-Jna2Bm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);